/**
 * Injected into proxied <head>. Routes **all** http(s) requests that would
 * hit remote origins (incl. CDNs) through `/proxy?url=…&ref=…` — not only
 * URLs on the main document origin, which caused ERR_NAME_NOT_RESOLVED.
 */
export function buildClientRuntimePatch(targetOrigin: string): string {
  const O = JSON.stringify(targetOrigin);
  return [
    "(function(){",
    "var O=" + O + ";",
    "function isSkip(s){if(s==null)return true;var t=String(s).trim().toLowerCase();",
    "if(!t)return true;if(t[0]==='#')return true;if(t.indexOf('data:')===0||t.indexOf('javascript:')===0)return true;",
    "if(t.indexOf('mailto:')===0||t.indexOf('tel:')===0||t.indexOf('about:')===0)return true;return t.indexOf('blob:')===0;}",
    "function baseUrl(){if(typeof document==='undefined')return O+'/';",
    "var b=document.querySelector('base[href]');if(b)try{return b.href}catch(e1){}return O+'/';}",
    "function isAlreadyProxied(s){if(typeof s!=='string')return false;",
    "if(s.indexOf('/proxy?url=')===0)return true;",
    "if(typeof location!=='undefined'&&location.origin)try{",
    "var a=new URL(s,location.href);if(a.origin===location.origin&&a.pathname.indexOf('/proxy')===0&&a.searchParams.get('url'))return true;",
    "}catch(e2){}return false;}",
    "function p(u){if(u==null||u==='')return u;if(isSkip(String(u)))return u;if(isAlreadyProxied(String(u)))return u;",
    "try{",
    "var s=String(u),x,r=(typeof location!=='undefined'&&location.href)?location.href:O+'/';",
    "if(s.indexOf('/proxy?url=')===0||isAlreadyProxied(s))return s;",
    "x=/^[a-zA-Z][a-zA-Z+.-]*:/.test(s)?new URL(s):new URL(s,baseUrl());",
    "if(x.protocol!=='http:'&&x.protocol!=='https:')return u;",
    "return '/proxy?url='+encodeURIComponent(x.href)+'&ref='+encodeURIComponent(r);",
    "}catch(e){}return u;}",
    "function srcsetP(v){return String(v).split(',').map(function(part){",
    "var a=part.trim().split(/\\s+/),u0=a[0];if(!u0)return part;var nu=p(u0);",
    "return a.length>1?nu+' '+a.slice(1).join(' '):nu;}).join(', ');}",
    "if(typeof window!=='undefined'&&typeof window.fetch==='function'){",
    "var f0=window.fetch;window.fetch=function(i,init){",
    "if(typeof i==='string')return f0.call(this,p(i),init);",
    "if(typeof Request!=='undefined'&&i&&typeof i==='object'&&i instanceof Request){",
    "var u=p(i.url);if(u===i.url)return f0.call(this,i,init);",
    "return f0.call(this,new Request(u,{method:i.method,headers:i.headers,body:i.body,mode:i.mode,",
    "credentials:i.credentials,cache:i.cache,redirect:i.redirect,referrer:i.referrer,",
    "integrity:i.integrity,keepalive:i.keepalive,signal:i.signal,referrerPolicy:i.referrerPolicy}));",
    "}",
    "return f0.call(this,i,init);};}",
    "if(window.XMLHttpRequest){",
    "var o=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){",
    "var a=[].slice.call(arguments);if(typeof a[1]==='string')a[1]=p(a[1]);return o.apply(this,a);};}",
    "var Img=Image;if(typeof Img!=='undefined'){",
    "var Im=function(w,h){var el=(typeof w==='number'||h!==undefined)?new Img(w,h):new Img();return el;};",
    "Im.prototype=Img.prototype;window.Image=Im;}",
    "var patch=function(proto,nam){if(!proto)return;try{",
    "var d=Object.getOwnPropertyDescriptor(proto,nam);if(!d||!d.set||!d.get)return;",
    "var oset=d.set,oget=d.get;Object.defineProperty(proto,nam,",
    "{configurable:true,enumerable:d.enumerable,",
    "get:function(){return oget.call(this);},",
    "set:function(v){return oset.call(this,nam==='srcset'||nam==='imagesrcset'?srcsetP(v):p(String(v)));}});}catch(x){}};",
    "if(typeof HTMLImageElement!=='undefined'){patch(HTMLImageElement.prototype,'src');patch(HTMLImageElement.prototype,'srcset');}",
    "if(typeof HTMLScriptElement!=='undefined')patch(HTMLScriptElement.prototype,'src');",
    "if(typeof HTMLIFrameElement!=='undefined')patch(HTMLIFrameElement.prototype,'src');",
    "if(typeof HTMLSourceElement!=='undefined'){patch(HTMLSourceElement.prototype,'src');patch(HTMLSourceElement.prototype,'srcset');}",
    "if(typeof HTMLVideoElement!=='undefined')patch(HTMLVideoElement.prototype,'src');",
    "if(typeof HTMLAudioElement!=='undefined')patch(HTMLAudioElement.prototype,'src');",
    "if(typeof HTMLEmbedElement!=='undefined')patch(HTMLEmbedElement.prototype,'src');",
    "if(typeof HTMLTrackElement!=='undefined')patch(HTMLTrackElement.prototype,'src');",
    "if(typeof HTMLObjectElement!=='undefined'){patch(HTMLObjectElement.prototype,'data');}",
    "if(typeof HTMLInputElement!=='undefined')patch(HTMLInputElement.prototype,'src');",
    "if(typeof HTMLLinkElement!=='undefined')patch(HTMLLinkElement.prototype,'href');",
    "if(typeof HTMLAnchorElement!=='undefined')patch(HTMLAnchorElement.prototype,'href');",
    "if(typeof HTMLFormElement!=='undefined')patch(HTMLFormElement.prototype,'action');",
    "if(typeof HTMLAreaElement!=='undefined')patch(HTMLAreaElement.prototype,'href');",
    "if(typeof Element!=='undefined'&&Element.prototype.setAttribute){",
    "var sa=Element.prototype.setAttribute;Element.prototype.setAttribute=function(n,v){n=String(n);",
    "if(v!=null&&/^(src|href|action|formaction|srcset|imagesrcset|poster|data)$/i.test(n)||",
    "(n.indexOf('data-')===0&&/src|href|url|set/i.test(n))){",
    "v=/^srcset$/i.test(n)||/imagesrcset/i.test(n)?srcsetP(String(v)):p(String(v));",
    "}",
    "return sa.call(this,n,v);};}",
    "if(typeof Worker!=='undefined'){",
    "var W=Worker;window.Worker=function(u,opt){",
    "if(u instanceof URL)return new W(p(u.href),opt);",
    "if(typeof u==='string')return new W(p(u),opt);",
    "return new W(u,opt);};window.Worker.prototype=W.prototype;}",
    "if(typeof window.EventSource!=='undefined'&&EventSource.prototype){",
    "var E=EventSource,Ev=function(u,cfg){if(u instanceof URL)return new E(p(u.href),cfg);",
    "if(typeof u==='string')return new E(p(u),cfg);return new E(u,cfg);};",
    "Ev.prototype=E.prototype;window.EventSource=Ev;}",
    "var psh=history.pushState,rst=history.replaceState;",
    "history.pushState=function(st,ti,ur){if(typeof ur==='string'&&ur)try{",
    "var u2=new URL(ur,O+'/');if(u2.origin===(new URL(O)).origin)ur=p(u2.href);}catch(e3){}return psh.apply(this,arguments);};",
    "history.replaceState=function(st,ti,ur){if(typeof ur==='string'&&ur)try{",
    "var u3=new URL(ur,O+'/');if(u3.origin===(new URL(O)).origin)ur=p(u3.href);}catch(e4){}return rst.apply(this,arguments);};",
    "document.addEventListener('click',function(e){",
    "var t=e.target,n=0;while(t&&t.tagName!=='A'&&n++<14)t=t.parentNode;",
    "if(!t||t.tagName!=='A')return;var h=t.getAttribute('href');if(!h||h[0]==='#')return;",
    "try{var w=new URL(t.href,location.href);if(w.protocol==='http:'||w.protocol==='https:'){",
    "e.preventDefault();e.stopImmediatePropagation?e.stopImmediatePropagation():0;location.assign(p(w.href));}}catch(b){}}",
    ",!0);",
    "})();",
  ].join("");
}
